/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.sistemAkademikApps.view;

import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import main.java.com.sistemAkademikApps.controller.AbsensiController;
import main.java.com.sistemAkademikApps.model.AbsensiModel;

/**
 *
 * @author hp
 */
public class AbsensiView extends javax.swing.JFrame {

    AbsensiModel absensiModel;
    AbsensiController absensiController;
    /**
     * Creates new form AbsensiView
     */
    public AbsensiView() throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
        
        absensiModel = new AbsensiModel();
        absensiController = new AbsensiController();
        absensiController.setAbsensiModel(absensiModel);
        absensiController.tampilData(this);
        absensiController.tampilKelas(this);
        absensiController.tampilKelasWakel(this);
        absensiController.tampilPertemuan(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcomboKet = new javax.swing.JComboBox<>();
        jcomboNama = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblAbsen = new javax.swing.JTable();
        jHasilPertemuan = new javax.swing.JTextField();
        jTxtPertemuan = new javax.swing.JTextField();
        btnSave = new rojerusan.RSMaterialButtonRectangle();
        SUBMIT1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel9 = new javax.swing.JLabel();
        jcomboKelas = new javax.swing.JComboBox<>();
        jTgl = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jBtnCari = new rojerusan.RSMaterialButtonRectangle();
        jBtnBack = new rojerusan.RSMaterialButtonRectangle();
        jHasilWakel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboKelasPilih = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboPertemuan = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/com/sistemAkademikApps/img/user(3).png"))); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABSENSI");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/com/sistemAkademikApps/img/user(3).png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 242, 310, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 40, 610));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcomboKet.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jcomboKet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Izin", "Sakit", "Alpha" }));
        jPanel2.add(jcomboKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 190, 40));

        jcomboNama.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jcomboNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcomboNamaMouseClicked(evt);
            }
        });
        jcomboNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboNamaActionPerformed(evt);
            }
        });
        jcomboNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcomboNamaKeyPressed(evt);
            }
        });
        jPanel2.add(jcomboNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Kelas :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 90, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Pertemuan :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nama :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Pertemuan ke-");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 130, 20));

        jTblAbsen.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTblAbsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA", "ID PERTEMUAN", "KETERANGAN"
            }
        ));
        jTblAbsen.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTblAbsen.setRowHeight(20);
        jTblAbsen.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(jTblAbsen);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 520, 200));

        jHasilPertemuan.setEditable(false);
        jHasilPertemuan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jHasilPertemuan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jHasilPertemuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 50, 40));

        jTxtPertemuan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(jTxtPertemuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 180, 40));

        btnSave.setBackground(new java.awt.Color(0, 153, 0));
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnSave.setText("SAVE");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 110, 50));

        SUBMIT1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        SUBMIT1.setText("SUBMIT");
        SUBMIT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SUBMIT1MouseClicked(evt);
            }
        });
        jPanel2.add(SUBMIT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 180, 50));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Wali Kelas : ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jcomboKelas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jcomboKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboKelasActionPerformed(evt);
            }
        });
        jPanel2.add(jcomboKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 110, 40));
        jPanel2.add(jTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 200, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Keterangan :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 120, -1));

        jBtnCari.setBackground(new java.awt.Color(102, 102, 102));
        jBtnCari.setText("CARI");
        jBtnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCariMouseClicked(evt);
            }
        });
        jBtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCariActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 70, 40));

        jBtnBack.setBackground(new java.awt.Color(255, 153, 0));
        jBtnBack.setText("BACK");
        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
        });
        jPanel2.add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 530, 120, 40));

        jHasilWakel.setEditable(false);
        jHasilWakel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel2.add(jHasilWakel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 160, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("Pertemuan :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Tanggal :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 90, 20));

        jPanel2.add(jComboKelasPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 90, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Kelas :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jComboPertemuan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel2.add(jComboPertemuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 266, 100, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1220, 610));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATA ABSENSI ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboNamaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcomboNamaKeyPressed

    private void jcomboNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcomboNamaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcomboNamaMouseClicked

    private void jcomboNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboNamaActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        try {
            // TODO add your handling code here:
            absensiController.tambahPertemuan(this);
            absensiController.tampilNama(this);
        } catch (SQLException ex) {
            Logger.getLogger(AbsensiView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AbsensiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void SUBMIT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUBMIT1MouseClicked
        try {
            // TODO add your handling code here:
            absensiController.tambahDataAbsen(this);
        } catch (SQLException ex) {
            Logger.getLogger(AbsensiView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AbsensiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SUBMIT1MouseClicked

    private void jcomboKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboKelasActionPerformed
        try {
            // TODO add your handling code here:
            absensiController.tampilWakel(this);
        } catch (SQLException ex) {
            Logger.getLogger(AbsensiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcomboKelasActionPerformed

    private void jBtnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCariMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            absensiController.tampilDataPerKelas(this);
        } catch (SQLException ex) {
            Logger.getLogger(AbsensiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnCariMouseClicked

    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        // TODO add your handling code here:
        MenuView menu = new MenuView();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsensiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsensiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsensiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsensiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AbsensiView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AbsensiView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JTable getjTblAbsen() {
        return jTblAbsen;
    }

    public JComboBox<String> getJcomboKet() {
        return jcomboKet;
    }

    public JComboBox<String> getJcomboNama() {
        return jcomboNama;
    }

    public JTextField getjTxtPertemuan() {
        return jTxtPertemuan;
    }

    public JTextField getjHasilPertemuan() {
        return jHasilPertemuan;
    }

    public JComboBox<String> getjComboKelas() {
        return jcomboKelas;
    }

    public JDateChooser getjTgl() {
        return jTgl;
    }

    public JTextField getjHasilWakel() {
        return jHasilWakel;
    }

    public JComboBox<String> getjComboKelasPilih() {
        return jComboKelasPilih;
    }

    public JComboBox<String> getjComboPertemuan() {
        return jComboPertemuan;
    }

    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle SUBMIT1;
    private rojerusan.RSMaterialButtonRectangle btnSave;
    private rojerusan.RSMaterialButtonRectangle jBtnBack;
    private rojerusan.RSMaterialButtonRectangle jBtnCari;
    private javax.swing.JComboBox<String> jComboKelasPilih;
    private javax.swing.JComboBox<String> jComboPertemuan;
    private javax.swing.JTextField jHasilPertemuan;
    private javax.swing.JTextField jHasilWakel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblAbsen;
    private com.toedter.calendar.JDateChooser jTgl;
    private javax.swing.JTextField jTxtPertemuan;
    private javax.swing.JComboBox<String> jcomboKelas;
    private javax.swing.JComboBox<String> jcomboKet;
    private javax.swing.JComboBox<String> jcomboNama;
    // End of variables declaration//GEN-END:variables

}
