/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.sistemAkademikApps.view;

import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import main.java.com.sistemAkademikApps.controller.SiswaController;
import main.java.com.sistemAkademikApps.model.SiswaModel;

/**
 *
 * @author HP
 */
public class FormDataSiswaView extends javax.swing.JFrame {

    SiswaModel siswaModel;
    SiswaController siswaController;
    /**
     * Creates new form FormDataSiswaView
     */
    public FormDataSiswaView() throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
                
        
        siswaModel = new SiswaModel();
        siswaController = new SiswaController();
        siswaController.setSiswaModel(siswaModel);
        siswaController.tampilData(this);
        siswaModel.kls();
        siswaController.kelas(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNisn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTtl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        comboKelas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSiswa = new javax.swing.JTable();
        radioP = new javax.swing.JRadioButton();
        radioL = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        comboCariKelas = new javax.swing.JComboBox<>();
        tglLahir = new com.toedter.calendar.JDateChooser();
        jBtnCari = new rojerusan.RSMaterialButtonRectangle();
        jBtnEdit = new rojerusan.RSMaterialButtonRectangle();
        jBtnHapus1 = new rojerusan.RSMaterialButtonRectangle();
        jBtnBack1 = new rojerusan.RSMaterialButtonRectangle();
        jBtnSimpan2 = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Data Siswa");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FORM DATA SISWA");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 47, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 140));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("PILIH KELAS :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 150, 50));

        txtNisn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtNisn.setPreferredSize(new java.awt.Dimension(200, 40));
        txtNisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNisnActionPerformed(evt);
            }
        });
        jPanel1.add(txtNisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 330, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("NISN :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 50));

        txtNama.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtNama.setPreferredSize(new java.awt.Dimension(200, 40));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 330, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NAMA :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 50));

        txtTtl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtTtl.setPreferredSize(new java.awt.Dimension(200, 40));
        txtTtl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTtlActionPerformed(evt);
            }
        });
        jPanel1.add(txtTtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 160, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("TTL :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 50));

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 340, 120));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("JENIS KELAMIN :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 140, 50));

        comboKelas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(comboKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 200, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ALAMAT :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 120, 50));

        jTableSiswa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NISN", "NAMA", "TEMPAT LAHIR", "TANGGAL LAHIR", "JENIS KELAMIN", "ALAMAT", "KELAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSiswa.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableSiswa.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jTableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSiswa);
        if (jTableSiswa.getColumnModel().getColumnCount() > 0) {
            jTableSiswa.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 590, -1));

        buttonGroup1.add(radioP);
        radioP.setText("Perempuan");
        radioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPActionPerformed(evt);
            }
        });
        jPanel1.add(radioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        buttonGroup1.add(radioL);
        radioL.setText("Laki-Laki");
        radioL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLActionPerformed(evt);
            }
        });
        jPanel1.add(radioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("KELAS :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 140, 50));

        jPanel1.add(comboCariKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 160, 40));
        jPanel1.add(tglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 150, 50));

        jBtnCari.setBackground(new java.awt.Color(153, 153, 153));
        jBtnCari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jBtnCari.setText("CARI");
        jBtnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCariMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 120, 40));

        jBtnEdit.setBackground(new java.awt.Color(0, 102, 255));
        jBtnEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jBtnEdit.setText("EDIT");
        jBtnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEditMouseClicked(evt);
            }
        });
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, 120, 40));

        jBtnHapus1.setBackground(new java.awt.Color(204, 0, 51));
        jBtnHapus1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jBtnHapus1.setText("HAPUS");
        jBtnHapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnHapus1MouseClicked(evt);
            }
        });
        jPanel1.add(jBtnHapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 120, 40));

        jBtnBack1.setBackground(new java.awt.Color(102, 102, 102));
        jBtnBack1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jBtnBack1.setText("BACK");
        jBtnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseClicked(evt);
            }
        });
        jPanel1.add(jBtnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 660, 120, 40));

        jBtnSimpan2.setBackground(new java.awt.Color(0, 204, 0));
        jBtnSimpan2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jBtnSimpan2.setText("SIMPAN");
        jBtnSimpan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSimpan2MouseClicked(evt);
            }
        });
        jPanel1.add(jBtnSimpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNisnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNisnActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTtlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTtlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTtlActionPerformed

    private void radioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPActionPerformed

    private void radioLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLActionPerformed

    private void jTableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSiswaMouseClicked
        try {
            // TODO add your handling code here:
            siswaController.tampilPerSiswa(this);
        } catch (ParseException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTableSiswaMouseClicked

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditActionPerformed

    private void jBtnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditMouseClicked
        try {
            // TODO add your handling code here:
            siswaController.editSiswa(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnEditMouseClicked

    private void jBtnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCariMouseClicked

        try {
            siswaController.tampilDataPerKelas(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }
           
            
    }//GEN-LAST:event_jBtnCariMouseClicked

    private void jBtnHapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHapus1MouseClicked
        try {
            // TODO add your handling code here:
            siswaController.hapusData(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnHapus1MouseClicked

    private void jBtnBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseClicked
        // TODO add your handling code here:
        MenuView menu = new MenuView();
        menu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jBtnBack1MouseClicked

    private void jBtnSimpan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSimpan2MouseClicked
        try {
            // TODO add your handling code here:
            siswaController.simpanData(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnSimpan2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataSiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataSiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataSiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataSiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormDataSiswaView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JTable getjTableSiswa() {
        return jTableSiswa;
    }

    public JComboBox<String> getComboJk() {
        return comboKelas;
    }

    public JTextArea getTxtAlamat() {
        return txtAlamat;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtNisn() {
        return txtNisn;
    }

    public JTextField getTxtTtl() {
        return txtTtl;
    }

    public JComboBox<String> getComboKelas() {
        return comboKelas;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JRadioButton getRadioL() {
        return radioL;
    }

    public JRadioButton getRadioP() {
        return radioP;
    }

    public JComboBox<String> getComboCariKelas() {
        return comboCariKelas;
    }

    public JDateChooser getTglLahir() {
        return tglLahir;
    }

    /*** edit button
     * try {
            // TODO add your handling code here:
            siswaController.editSiswa(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
            * 
            * 
            * //buton simpan
            *  try {
            siswaController.simpanData(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        * 
        * 
        * //hapus
        * try {
            // TODO add your handling code here:
            siswaController.hapusData(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        * 
        *  MenuView menu = new MenuView();
        menu.setVisible(true);
        this.setVisible(false);
        * 
        * 
        * //cari
        * try {
            siswaController.tampilDataPerKelas(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }
     */
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboCariKelas;
    private javax.swing.JComboBox<String> comboKelas;
    private rojerusan.RSMaterialButtonRectangle jBtnBack1;
    private rojerusan.RSMaterialButtonRectangle jBtnCari;
    private rojerusan.RSMaterialButtonRectangle jBtnEdit;
    private rojerusan.RSMaterialButtonRectangle jBtnHapus1;
    private rojerusan.RSMaterialButtonRectangle jBtnSimpan2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSiswa;
    private javax.swing.JRadioButton radioL;
    private javax.swing.JRadioButton radioP;
    private com.toedter.calendar.JDateChooser tglLahir;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNisn;
    private javax.swing.JTextField txtTtl;
    // End of variables declaration//GEN-END:variables




}
