/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.sistemAkademikApps.view;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.java.com.sistemAkademikApps.controller.MenuController;
import main.java.com.sistemAkademikApps.controller.SiswaController;
import main.java.com.sistemAkademikApps.model.Koneksi;
import main.java.com.sistemAkademikApps.model.MenuModel;

/**
 *
 * @author HP
 */
public class MenuView extends javax.swing.JFrame {
    
    MenuController menuController;
    MenuModel menuModel;
    SiswaController siswaController;
    Connection con;
    
    public MenuView() {
        menuController = new MenuController();
        //menuController.setMenuModel(menuModel);
        siswaController = new SiswaController();
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        BtnKleuar = new rojerusan.RSMaterialButtonRectangle();
        BtnFormSiswa = new rojerusan.RSMaterialButtonRectangle();
        BtnKelas = new rojerusan.RSMaterialButtonRectangle();
        BtnSiswa = new rojerusan.RSMaterialButtonRectangle();
        BtnAbout = new rojerusan.RSMaterialButtonRectangle();
        BtnAbsen2 = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU ");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/com/sistemAkademikApps/img/usher.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 210, 180));

        BtnKleuar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        BtnKleuar.setText("KELUAR");
        BtnKleuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnKleuarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnKleuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 310, 50));

        BtnFormSiswa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        BtnFormSiswa.setText("FORM DATA SISWA");
        BtnFormSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnFormSiswaMouseClicked(evt);
            }
        });
        jPanel1.add(BtnFormSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 310, 50));

        BtnKelas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        BtnKelas.setText("FORM DATA KELAS");
        BtnKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnKelasMouseClicked(evt);
            }
        });
        BtnKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKelasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 310, 50));

        BtnSiswa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        BtnSiswa.setText("DATA SISWA");
        BtnSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSiswaMouseClicked(evt);
            }
        });
        jPanel1.add(BtnSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 310, 50));

        BtnAbout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        BtnAbout.setText("ABOUT US");
        BtnAbout.setActionCommand("ABOUT US");
        BtnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAboutMouseClicked(evt);
            }
        });
        jPanel1.add(BtnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 310, 50));

        BtnAbsen2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        BtnAbsen2.setText("ABSENSI");
        BtnAbsen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAbsen2MouseClicked(evt);
            }
        });
        jPanel1.add(BtnAbsen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 310, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 600, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFormDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFormDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnFormDataMouseClicked

    private void BtnKleuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnKleuarMouseClicked
        // TODO add your handling code here:
        LoginView login = new LoginView();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnKleuarMouseClicked

    private void BtnFormSiswa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFormSiswa1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnFormSiswa1MouseClicked

    private void BtnSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSiswaMouseClicked
        try {
            menuController.tampilMenuSiswa();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BtnSiswaMouseClicked

    private void BtnKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnKelasMouseClicked
        try {
            // TODO add your handling code here:
            menuController.tampilFormKelas();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnKelasMouseClicked

    private void BtnFormSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFormSiswaMouseClicked

        try {
            // TODO add your handling code here:
            menuController.tampilMenuForm();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BtnFormSiswaMouseClicked

    private void BtnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAboutMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            menuController.tampilMenuAbout();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAboutMouseClicked

    private void BtnKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKelasActionPerformed

    private void BtnAbsen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAbsen2MouseClicked
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            menuController.tampilMenuAbsen();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAbsen2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle BtnAbout;
    private rojerusan.RSMaterialButtonRectangle BtnAbsen2;
    private rojerusan.RSMaterialButtonRectangle BtnFormSiswa;
    private rojerusan.RSMaterialButtonRectangle BtnKelas;
    private rojerusan.RSMaterialButtonRectangle BtnKleuar;
    private rojerusan.RSMaterialButtonRectangle BtnSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
