/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.sistemAkademikApps.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import main.java.com.sistemAkademikApps.controller.SiswaController;
import main.java.com.sistemAkademikApps.model.SiswaModel;

/**
 *
 * @author HP
 */
public class SiswaView extends javax.swing.JFrame {

    SiswaModel siswaModel;
    SiswaController siswaController;
    /**
     * Creates new form SiswaView
     */
    public SiswaView() throws SQLException {
        initComponents();
        
        setLocationRelativeTo(this);
        
        siswaModel = new SiswaModel();
        siswaController = new SiswaController();
        siswaController.setSiswaModel(siswaModel);
        siswaController.tampilDataSiswa(this);
        siswaController.kelasSiswa(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSiswa = new javax.swing.JTable();
        jBtnBack = new rojerusan.RSMaterialButtonRectangle();
        jLabel2 = new javax.swing.JLabel();
        comboCariKelas = new javax.swing.JComboBox<>();
        jBtnCari = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA SISWA");
        setBounds(new java.awt.Rectangle(0, 0, 800, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA SISWA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        jTableSiswa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NISN", "NAMA ", "TEMPAT LAHIR", "TANGGAL LAHIR", "JENIS KELAMIN", "ALAMAT", "KELAS"
            }
        ));
        jScrollPane1.setViewportView(jTableSiswa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 690, -1));

        jBtnBack.setBackground(new java.awt.Color(153, 153, 153));
        jBtnBack.setText("BACK");
        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, 140, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("PILIH KELAS :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 150, 50));

        comboCariKelas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(comboCariKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 160, 40));

        jBtnCari.setBackground(new java.awt.Color(153, 153, 153));
        jBtnCari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jBtnCari.setText("CARI");
        jBtnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCariMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        // TODO add your handling code here:
        MenuView menu = new MenuView();
        menu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCariMouseClicked

       try {
            siswaController.tampilDataPerKelasSiswa(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormDataSiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBtnCariMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SiswaView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SiswaView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JTable getjTableSiswa() {
        return jTableSiswa;
    }

    public JComboBox<String> getComboCariKelas() {
        return comboCariKelas;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCariKelas;
    private rojerusan.RSMaterialButtonRectangle jBtnBack;
    private rojerusan.RSMaterialButtonRectangle jBtnCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSiswa;
    // End of variables declaration//GEN-END:variables
}
